#!/bin/bash
source /etc/default/gemstone
source $GEMSTONE_CONFIG

# check for the license key
if [ -s $GEMSTONE/seaside/etc/gemstone.secret ]; then
      . $GEMSTONE/seaside/etc/gemstone.secret
else
      echo 'Missing password file $GEMSTONE/seaside/etc/gemstone.secret'
      exit 1
 fi

# stop all the gems
for i in `ls -d /etc/service/gs_*`; do
    sudo svc -d $i
done


echo "Starting stone: $GEMSTONE_NAME"

$GEMSTONE/seaside/bin/stopGemstone $GEMSTONE_CURATOR_PASS

# start all the gems, which use waitstone to wait on the gemstone instance
for i in `ls -d /etc/service/gs_*`; do
    sudo svc -u $i
done



exec setuidgid $GEMSTONE_USER fghack $GEMSTONE/bin/startstone $GEMSTONE_NAME -z $GEMSTONE_SYS_CONF -l $GEMSTONE_LOGDIR/$GEMSTONE_NAME.log
