#!/bin/bash
source /etc/default/gemstone
source $GEMSTONE_CONFIG
$GEMSTONE/bin/waitstone $GEMSTONE_NAME 2
# Create the stats directory if it's not there
mkdir -p /home/$GEMSTONE_USER/stats/60-second
chown -R $GS_OWNER /home/$GEMSTONE_USER/stats
cd /home/$GEMSTONE_USER/stats/60-second
setuidgid $GEMSTONE_USER $GEMSTONE/bin/statmonitor $GEMSTONE_NAME -rAzq -h 24 -i 60
