---
-
  hosts: squeak
  sudo: true
  vars_files:
    - vars/main.yml
    - vars/squeakPlatform.yml
  roles:
    - {role: ia32-libs, when: ansible_userspace_bits == "64"} #install 32 bit libraries on 64 bit platforms
    - squeak
    - nginx
    
...
