#!/bin/bash

# for use by daemontools to run the tropo server
source {{gemstone_config}}
scriptpath=$(dirname $0)
[ -r $scriptpath/config.local ] && source $scriptpath/config.local
$GEMSTONE/bin/waitstone $GEMSTONE_NAME 2
exec setuidgid {{deploy_user $GEMSTONE/seaside/bin/tropoRunGem daemon-tropo $GEM_PORT
