---   

    - name: Add deployment user
      user: name={{deploy_user}} password=$deploy_password shell=/bin/bash
    - name: Add authorized deploy key
      authorized_key: user={{deploy_user}} key='$FILE(id_rsa.pub)'
    - name: Remove sudo group rights
      lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent
    - name: Add deploy user to sudoers
      lineinfile: dest=/etc/sudoers regexp="{{deploy_user}} ALL" line="{{deploy_user}} ALL=NOPASSWD:ALL" state=present
    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: Restart ssh
    - name: Install unattended-upgrades
      apt: pkg=unattended-upgrades state=present
    - name: Adjust APT update intervals
      copy: src=config/apt_periodic dest=/etc/apt/apt.conf.d/10periodic
    - name: Make sure unattended-upgrades only installs from $ubuntu_release security
      lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent
    - name: update apt cache
      apt: update_cache=yes upgrade=dist cache_valid_time=3600
    - name: install preliminary packages
      apt: pkg={{item}} state=installed
      with_items:
        - fail2ban
        - mosh
        - htop
        - screen
        - aptitude
        - emacs
        - daemontools
        - git
        - python-software-properties
        - rsync
        - openssl
        - sudo
        - curl
        - wget

    - name: Setup ufw
      shell: ufw allow 22/tcp
    - name: Setup ufw
      shell: ufw allow 443/tcp
    - name: Setup ufw
      shell: ufw allow 60023/udp
    - name: Enable ufw
      shell: echo 'y' | ufw enable
    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
    - name: reboot the server
      command: /sbin/reboot
