---
- name: make sure the Debian system knows to support i386
  command: dpkg --add-architecture i386
  when: ansible_distribution == "Debian"
- name: install the debian 32 bit libraries
  apt: name={{item}} state=present update_cache=yes cache_valid_time=1800
  with_items:
    - libgd2-xpm
    - libgd2-xpm:i386
    - ia32-libs
  when: ansible_distribution == "Debian"
- name: install the 32 bit libraries for Ubuntu64 bit platform
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - libgd2-xpm
    - libgd2-xpm:i386
    - ia32-libs-multiarch:i386
  when: ansible_distribution == "Ubuntu"
